# Generated by Django 5.2.6 on 2025-09-16 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-is_featured', '-created_at'], 'permissions': [('can_publish_project', 'Peut publier des projets'), ('can_publish_post', 'Peut publier des articles')], 'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.AddField(
            model_name='post',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
