# Generated by Django 5.2.6 on 2025-09-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_project_options_post_submitted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approuvé'),
        ),
    ]
